### PR TITLE
Testing PR/merge builds

### PR DESCRIPTION
**Pull request by jgwerner**
Tests.

### CODE REVIEW

**Comment by raygesualdo** [comment]
Interested in why we're not testing merged commits. It would be trivial to test master yml vs. PR yml.

**Comment by jgwerner** [comment]
Ideally, we would test on merge to master. But these first tests are to test on PR's only, since the env vars obtained from Travis to populate slug & branch come from PR info.

**Comment by raygesualdo** [comment]
We have access to the same information when not in a pull request though.

**Comment by jgwerner** [comment]
Yes but the current script only uses PR slugs. Later I'll add ones for merges to master.

**Pull request closed without merging**
